// Code generated by "stringer -type=Artist -linecomment"; DO NOT EDIT.

package stringer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArtistATB-0]
	_ = x[ArtistPVD-1]
	_ = x[ArtistASOT-2]
}

const _Artist_name = "andrepaularmin"

var _Artist_index = [...]uint8{0, 5, 9, 14}

func (i Artist) String() string {
	if i < 0 || i >= Artist(len(_Artist_index)-1) {
		return "Artist(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Artist_name[_Artist_index[i]:_Artist_index[i+1]]
}
