// Code generated by "stringer -type=Hospital -output=medicine_homes.go"; DO NOT EDIT.

package stringer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Central-0]
	_ = x[Main-1]
}

const _Hospital_name = "CentralMain"

var _Hospital_index = [...]uint8{0, 7, 11}

func (i Hospital) String() string {
	if i < 0 || i >= Hospital(len(_Hospital_index)-1) {
		return "Hospital(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Hospital_name[_Hospital_index[i]:_Hospital_index[i+1]]
}
